{% set version = "0.4.0" %}

package:
  name: neurodent
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/neurodent/neurodent-{{ version }}.tar.gz
  sha256: 5ba1ca538eb9a8544d6389ae13af9ea6736b221473d98e2f8d3900ec5ebf4924

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - mne
    - mne-connectivity
    - pandas
    - spikeinterface
    - probeinterface
    - scipy
    - dask-core
    - distributed
    - dask-jobqueue
    - seaborn
    - pyarrow
    - statannotations
    - statsmodels
    - openpyxl
    - appnope
    - zarr >=2.18.3
    - scikit-learn >=1.7.2

test:
  imports:
    - neurodent
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://josephdong1000.github.io/neurodent
  summary: Rodent EEG analysis tools
  dev_url: https://github.com/josephdong1000/neurodent
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - josephdong1000
